### PR TITLE
Album ids are allowed to be strings, so don't cast.

### PR DESCRIPTION
**Pull request by mayhem**
As it says on the tin -- don't force album ids to be ints, strings are allowed.

### CODE REVIEW

**Comment by crustymonkey** [comment]
Is this causing a problem on the server-side?  The reason it's cast is as a validation that it's actually an integer value being passed into the method.

**Comment by crustymonkey** [comment]
I did validate this against a stock Subsonic server and had no issues, but if you're using some alternate server-side software, let me know.

**Comment by mayhem** [comment]
In the https://github.com/metabrainz/listenbrainz-content-resolver I am using py-sonic to access Navidrome, Funkwhale and Gonic. Navidrome uses string album ids and I think Funkwhale does too -- which means that I can't my software against a funkwhale installation currently.

**Comment by crustymonkey** [comment]
So, changing those to strings actually makes the requests work?  That seems really odd as the requests are either made via a POST or GET, but in both cases it's urlencoded data:

```
    def _getRequest(self, viewName, query={}):
        qdict = self._getBaseQdict()
        qdict.update(query)
        url = '%s:%d/%s/%s' % (self._baseUrl, self._port, self._serverPath,
            viewName)
        req = urllib.request.Request(url, urlencode(qdict).encode('utf-8'))

        if self._useGET:
            url += '?%s' % urlencode(qdict)
            req = urllib.request.Request(url)

        return req
```

Due to that fact, it should make zero difference if the cast validation is done.  In the case of the albumId, it's going to be `id=1234` as there's no type distinction between strings and ints.  The only place it would matter is if it was a POST with a JSON body, which does actually distinguish between types, but that's not the case here.

**Comment by mayhem** [comment]
There is no point in arguing this anymore -- its a tiny change and you don't seem to believe me that it fixes the problem and that your implementation is currently broken. Going forward I'll subclass or just find a different library.

**Comment by crustymonkey** [comment]
Hold on.  First off, my implementation isn't "broken".  It's meant to work with stock Subsonic and it does that just fine.  Second, I'm not implying you're lying.  It just doesn't make any sense as to why the change would make any difference, as I explained above.  I just want to understand *why* this change makes any difference because it *shouldn't*.  I never said that I wouldn't accept the change as it won't break anything by accepting it, I just wanted to figure what was missing in this such that the change is necessary.

**Pull request merged**
